### ISSUE TITLE
UPN and e-mail not updated on enable 

### ISSUE THREAD

**Issue by mikevanacknowledge** [Tools4everBV/HelloID-Conn-Prov-Target-AFAS-Profit-Users#2]
In case the update step is skipped - and the UPN was not yet available on create, the UPN and e-mail address is not provisioned to AFAS until a new update is triggered due to changes in AFAS. This problem is solved when adding the 'EmAd' and 'Upn' fields to the KnUser scope in the enable step (and providing it with the correct value from the connected AD target) - identical to the create and update step. Maybe add this in the default enable script?

**Comment by rschouten97** [comment]
Hi @mikevanacknowledge , the use case you describe is not a use case we come across often if ever.
In the "as it should be" scenario the UPN and/or e-mail address should always be available before provisioning to AFAS. This can be enforced by making the system dependent on the target system with the UPN and/or e-mail address, e.g. Active Directory.

You are free to add the provided solution to the specific use cases where this is needed, but we do not see this as the "default" or "should be" use case.

Of course, if you come across this use case (more) often, please do let us know and we will review this again.
